# Generated by Django 3.2.5 on 2021-08-22 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AkunBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bank', models.TextField()),
                ('nomor_rekening', models.TextField()),
                ('nama_pemilik', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cabang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField()),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.TextField()),
                ('alamat', models.TextField()),
                ('kota', models.TextField()),
                ('telpon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_resi', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('colly', models.TextField()),
                ('kg', models.TextField()),
                ('pengirim', models.TextField()),
                ('penerima', models.TextField()),
                ('tujuan', models.TextField()),
                ('nominal', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField()),
                ('role', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
