# Generated by Django 3.2.5 on 2021-08-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='nama_spv',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='telfon_spv',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
