# Generated by Django 3.2.5 on 2021-09-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210826_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='kota',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
