# Generated by Django 3.2.5 on 2021-09-07 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_penjualan_kota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.pelanggan')),
                ('penjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.penjualan')),
            ],
        ),
    ]
